package com.example.cryptotrackerapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "time_table")
data class TimeSery(
    val alt_rank: Int,
    val alt_rank_30d: Int,
    val asset_id: Int,
    val average_sentiment: Double,
    val close: Double,
    val correlation_rank: Double,
    val galaxy_score: Double,
    val high: Double,
    val low: Double,
    val market_cap: Long,
    val market_cap_global: Long,
    val market_cap_rank: Int,
    val market_dominance: Double,
    val medium: Int,
    val news: Int,
    val `open`: Double,
    val percent_change_24h: Double,
    val percent_change_24h_rank: Int,
    val price_btc: Int,
    val price_score: Double,
    val reddit_comments: Int,
    val reddit_comments_score: Int,
    val reddit_posts: Int,
    val reddit_posts_score: Int,
    val sentiment_absolute: Int,
    val sentiment_relative: Int,
    val social_contributors: Int,
    val social_dominance: Double,
    val social_impact_score: Double,
    val social_score: Int,
    val social_score_24h_rank: Int,
    val social_volume: Int,
    val social_volume_24h_rank: Int,
    val social_volume_global: Int,
    @PrimaryKey
    val time: Int,
    val tweet_favorites: Int,
    val tweet_followers: Int,
    val tweet_quotes: Int,
    val tweet_replies: Int,
    val tweet_retweets: Int,
    val tweet_sentiment1: Int,
    val tweet_sentiment2: Int,
    val tweet_sentiment3: Int,
    val tweet_sentiment4: Int,
    val tweet_sentiment5: Int,
    val tweet_sentiment_impact1: Int,
    val tweet_sentiment_impact2: Int,
    val tweet_sentiment_impact3: Int,
    val tweet_sentiment_impact4: Int,
    val tweet_sentiment_impact5: Int,
    val tweet_spam: Int,
    val tweets: Int,
    val unique_url_shares: Int,
    val url_shares: Int,
    val volatility: Double,
    val volume: Double,
    val volume_24h_rank: Int,
    val youtube: Int
)